### PR TITLE
Use filter_vertical for ManyToManyFields in admin

### LINKED ISSUE #272: Consider using filter_horizontal or filter_vertical for ManyToManyFields in admin
Would it be possible to use [`filter_horizontal`](https://docs.djangoproject.com/en/dev/ref/contrib/admin/#django.contrib.admin.ModelAdmin.filter_horizontal) or [`filter_vertical`](https://docs.djangoproject.com/en/1.11/ref/contrib/admin/#django.contrib.admin.ModelAdmin.filter_vertical) for the `ManyToManyFields` in the admin?

That would make it easier to select mission waypoints, select search grid points and select targets, and would also make it a lot easier for new users to distinguish between the available options and the selected options.

### PR DESCRIPTION
**Pull request by legonigel**
Also add some custom CSS to the admin page to allow the filter
vertical to scroll, becasue by default on chrome they do not scroll horizontally and
many of the models have very long string representations.

Closes #272

### CODE REVIEW

**Comment by legonigel** [comment]
Before:
image

After:
image

**Comment by pmtischler** [comment]
Does it not scroll because it fills the body and the body can scroll?

**Comment by legonigel** [comment]
It doesn't fill the body or scroll horizontally by default, which makes some data not visible at all. 
This might not apply to all browsers but by default [chromium applies `overflow-x:hidden` to selects](https://chromium.googlesource.com/chromium/blink/+/master/Source/core/css/html.css#777).
It could be fixed by manually specifying a width for the select as well, but I would have to investigate how that throws off other elements, because the select's div is floating.

**Comment by legonigel** [comment]
This is what it looks like without the custom CSS on Chromium, on FireFox the layout looks identical.
image

**Comment by pmtischler** [comment]
Sgtm

**Comment by foochuanwei** [comment]
@legonigel 'filter_verical' -> 'filter_vertical'?

**Comment by pmtischler** [comment]
Made unnecessary by #281

In the future, please don't send a PR if you're not going to go through a timely review process.

**Comment by legonigel** [comment]
@pmtischler What else was I expected to do to that pull request? What caused this pull request to be closed instead of merged?

**Pull request closed without merging**
