### PR TITLE
Fix healthcheck by checking pg_isready

### LINKED ISSUE #273: Database fails to start in time for loaddata during docker build
When running server/build.sh the database fails to start in time to load the data from Django, causing the build to fail.

```Removing intermediate container b75c8eb706aa
Step 20/23 : RUN sudo service postgresql start &&     sleep 5 &&     python manage.py loaddata fixtures/test_fixture.yaml
 ---> Running in b7c087cf2fba
 * Starting PostgreSQL 9.3 database server
   ...done.
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/loaddata.py", line 59, in handle
    with transaction.atomic(using=self.using):
  File "/usr/local/lib/python2.7/dist-packages/django/db/transaction.py", line 150, in __enter__
    if not connection.get_autocommit():
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 286, in get_autocommit
    self.ensure_connection()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/postgresql_psycopg2/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 179, in connect
    connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: FATAL:  the database system is starting up
FATAL:  the database system is starting up

The command '/bin/sh -c sudo service postgresql start &&     sleep 5 &&     python manage.py loaddata fixtures/test_fixture.yaml' returned a non-zero code: 1
```

### PR DESCRIPTION
**Pull request by legonigel**
Previous healthcheck using tcp packets was not reliable.

Fixes #273

### CODE REVIEW

**Comment by pmtischler** [comment]
Made unnecessary by #281

In the future, please don't send a PR if you're not going to go through a timely review process.

**Comment by legonigel** [comment]
@pmtischler What do I need to do to go through a timely review process. What else is expected of me? I'd be happy to have my code reviewed, but I don't know of any process in place for such a thing.

**Comment by pmtischler** [comment]
If you send a PR, I may add comments and those should be addressed, and then we iterate until its ready to be merged. The original PR and comments were sent ~25d ago and were not addressed.

**Comment by legonigel** [comment]
There were no comments on the commit or the code? What else should I have changed  if there were no comments? I cannot merge the code myself?

**Comment by pmtischler** [comment]
screenshot from 2017-08-05 15-04-59

**Comment by legonigel** [comment]
This review is not visible to me.

**Comment by pmtischler** [comment]
That's weird. I'll try comments next time.

**Comment by legonigel** [comment]
It's probably because I'm not a member of the organization. Maybe it's an option on the review itself.

**Comment by legonigel** [comment]
I believe I would be able to see the review if I have Read access to the repo, or organization, but I'm not certain.

**Comment by prattmic** [comment]
Phil, you need to click "Submit Review". All of your comments are just drafts until then.

**Comment by pmtischler** [comment]
Ah, that explains it. Sorry about that everyone.

**Pull request closed without merging**
