### PR TITLE
Fix bug in evaluate_teams dedupe logs.

### PR DESCRIPTION
**Pull request by pmtischler**

### CODE REVIEW

**Comment by prattmic** [comment]
How did this pass tests before?

**Comment by pmtischler** [comment]
Afk atm, but it would need more than one log to be exposed.

**Comment by prattmic** [comment]
We should try to add regression tests for this.

**Comment by pmtischler** [comment]
Yes we should. I checked the data and we do have multiple telemetry posts per user, which is odd.

**Comment by pmtischler** [comment]
Figured it out. If it returns only 1 flight period then it won't do the duplicate check either.

I added a regression test by adding an additional flight period, and validated it would have caught it. PTAL

**Comment by prattmic** [comment]
LGTM

**Pull request merged**
